### ISSUE TITLE
Postgresql Missing Function

### ISSUE THREAD

**Issue by ghost** [AndreasWBartels/JGISShell#1]
Hi
Accessing my Postgresql database with PostGis 3 installed.
I see the list of tables representing the layers within JGISShell.
However when tying to access the layer. I get the error below. The function is not in the database.
Database schema owned by the user specified in the connection, who has DBA privileges.
Access the database with mapsever / openlayers via WMS works.
java.io.IOException: org.postgresql.util.PSQLException: ERROR: function st_estimated_extent(name, name, name) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 251
	at net.anwiba.spatial.database.layer.io.AbstractDatabaseLayerMetaDataReader.getGeometryMetaData(AbstractDatabaseLayerMetaDataReader.java:92)
	at net.anwiba.spatial.database.layer.io.AbstractDatabaseLayerDescriptionReader.read(AbstractDatabaseLayerDescriptionReader.java:65)
	at net.anwiba.spatial.database.layer.io.AbstractDatabaseLayerDescriptionReader.read(AbstractDatabaseLayerDescriptionReader.java:45)
	at net.anwiba.jgisshell.swing.viewer.module.layer.LayerDataAccessOperatorsRegistry.read(LayerDataAccessOperatorsRegistry.java:229)
	at net.anwiba.spatial.swing.map.action.LoadLayerNodeInViewProcess.execute(LoadLayerNodeInViewProcess.java:82)
	at net.anwiba.commons.thread.process.ProcessRunner.run(ProcessRunner.java:83)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at net.anwiba.commons.thread.queue.WorkQueue$ProcessScheduledFuture.run(WorkQueue.java:77)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: function st_estimated_extent(name, name, name) does not exist

**Comment by ghost** [comment]
update/correction
st_estimatedextent(text,text,text) 
st_estimatedextent(text,text)
st_estimatedextent(text,text,text,bool)  

do exist in the same database as the layer tables.
Right clicking on a table and selecting Properties gives the following error

Caused by: org.postgresql.util.PSQLException: ERROR: function st_estimated_extent(name, name, name) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 251
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at net.anwiba.spatial.database.postgis.layer.utilities.PostGisUtilities.getGeometryMetaData(PostGisUtilities.java:650)
	at net.anwiba.spatial.database.postgis.layer.PostGisLayerMetaDataReader.getGeometryMetaData(PostGisLayerMetaDataReader.java:58)
	at net.anwiba.spatial.database.layer.io.AbstractDatabaseLayerMetaDataReader.getGeometryMetaData(AbstractDatabaseLayerMetaDataReader.java:90)
	... 7 more

**Comment by AndreasWBartels** [comment]
Should be fixed with version 1.1.124 unstable
